spring:
    datasource:
        name: lifecat
        url: jdbc:mysql://111.230.244.153:3306/catdb
        username: root
        password: wangshihao
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
#    activemq:
#        broker-url: tcp://127.0.0.1:61616
#        user: admin
#        password: admin
#    jms:
#        pub-sub-domain: true

mybatis:
    mapperLocations: classpath*:mapper/*.xml
    typeAliasesPackage: com.ten.entity