server:
  port: 8080

# mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/你的数据库名?useUnicode=true&characterEncoding=utf8
    username: 账号
    password: 密码

  # mybatis
  # 对应实体类的包名
mybatis:
  mapperLocations: classpath:mapper/*.xml