spring:
    datasource:
        name: aditum_mocker
        url: jdbc:mysql://localhost:3306/aditum_mocker
        username: root
        password: wangshihao
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
#    activemq:
#        broker-url: tcp://127.0.0.1:61616
#        user: admin
#        password: admin
#    jms:
#        pub-sub-domain: true

mybatis:
    mapperLocations: classpath*:mapper/*.xml
    typeAliasesPackage: com.ten.aditum.back.entity

# apollo 客户端配置
app:
  id: SampleApp

apollo:
  meta: http://127.0.0.1:8080
  bootstrap:
    enabled: true
    # 使用公共命名空间和back微服务私有命名空间
    namespaces: application,TEST1.back