server:
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
  port: 9006

spring:
    datasource:
        name: aditum
        url: jdbc:mysql://47.100.236.64:3306/aditum
        username: root
        password: wangshihao
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapperLocations: classpath*:mapper/*.xml
    typeAliasesPackage: com.ten.aditum.back.entity